### ISSUE TITLE
Recording dependencies for static files

### ISSUE THREAD

**Issue by pngwjpgh** [timbertson/gup#14]
Given a file `a` whose build process depends on the content of `b` and the content of all files referenced in `b` (e.g. via include statements in some languages).

Assume now that `b` does not need to be built (e.g. a configuration file of sorts) but references a file `c` (which might need to be built).

How would one record this dependency for gup?

Currently I have a buildscript for `b` that calls `gup -u c` and writes a constant string to `b` (`$1`, actually), which I find to subvert the purpose of having a buildscript in the first place.

Recording the dependency on `c` directly in `a`s buildscript seems a bad idea to me, since `b` might at any point stop referencing `c`.

Calling `gup --leave` in `b`s script instead of emitting a constant string has the unfortunate side effect of marking `b` as built by gup meaning it will be deleted by `gup --clean` (also it emits a warning, see #13).

**Comment by timbertson** [comment]
Good question. What I'd do is to make a meta-target, e.g. `b.transitive`. In the builder (`b.transitive.gup`), it might look like:

```
#!bash -eu
gup -u b # depend on contents of `b`
gup -u $(cat b) # depend on files referenced by `b` (obviously yours would need to be smarter)
touch "$1" # mark as done
```

Then, `a` would depend not on `b` directly, but on `b.transitive`. This is similar to an approach I use for entire directories of files - depend on some `directory/.stamp`, the builder for which depends on each file recursively in `directory/`.

What do you think, does that solve your problem? It's still a little unclean in that `a` has to know that it doesn't just depend on `b` but on `b.transitive`. But it's a safer hack than having `b` built directly because of the `--clean` issue you mentioned.

**Comment by timbertson** [comment]
Alternatively you rename `b` to `b.in`, then the `b.transitive` target just becomes `b`. Instead of `touch "$1"` you could `cp b.in "$1"` as the last line in the builder. Then everyone can just depend on `b`, and only the builder for `b` has to know about `b.in`.

**Comment by pngwjpgh** [comment]
I'm not really a fan of either (constant string in build script or `b.in`) method; ideally there would be an option to `--leave` to prevent the result from being cleaned up later…

I'm not clear on the structure of the logs gup keeps on what it built and why; would such a thing be easily doable?

**Comment by timbertson** [comment]
It might be technically possible, but it could also make things confusing. `gup clean` works on the assumption that if a target _can_ be built, then it can be safely deleted. `gup --leave` could leave some metadata around which `--clean` respects, but I don't really want to go down that path. It's much less prone to confusion if a target is either buildable _and_ disposable, or neither.

(for example, `gup --clean --metadata` would have to erase the record of "this file was built but shouldn't be deleted", which would cause the _next_ `gup --clean` to remove it anyway, which is a pretty confusing bug)

FWIW, `--leave` is typically meant for scripts which use other build tools which don't support writing to "$1", or which are smart enough not to touch the target when it doesn't need building. By using `--leave` to make a source file also a target, technically you've created a circular dependency (building `b` depends on the current contents of `b`), which I wouldn't encourage. The workarounds are a little inconvenient, but they are also conceptually straightforward.

**Comment by pngwjpgh** [comment]
> The workarounds are a little inconvenient, but they are also conceptually straightforward.
True

Thank you for the help :-)
