### ISSUE TITLE
'pipes' slated for removal in Python 3.13

### ISSUE THREAD

**Issue by michelschinz** [timbertson/gup#21]
Hello,

I started getting these warnings when running `gup` with the latest version of Python:
```
/usr/local/bin/gup:1582: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  from pipes import quote
```

They are not a big problem for me, as I can keep using older versions of Python to run `gup`, but I just wanted to let you know in case you didn't yet.

Thanks a lot for gup, by the way, which I use daily and really like!

**Comment by timbertson** [comment]
Thanks for noticing, I've taken this out now as of cbc3b151dda33663cb7a723a6365057915f717d5 👍
