### ISSUE TITLE
New warning about invalid escape sequence \s

### ISSUE THREAD

**Issue by michelschinz** [timbertson/gup#22]
Hello,

After upgrading Python to 3.12.2, I get the following warning when running gup:
```
gup:1068: SyntaxWarning: invalid escape sequence '\s'
```
the line in question reads:
``` python
new_rule = not re.match('^\s', line)
```
and the fix is probably just to use a raw string:
``` python
new_rule = not re.match(r'^\s', line)
```

I've applied that change to my version of gup, and it seems to work.

**Comment by timbertson** [comment]
Thanks for letting me know 👍
