### ISSUE TITLE
'0install add gup' as per the README fails

### ISSUE THREAD

**Issue by lunakid** [timbertson/gup#9]
(I'm a complete newbie with 0install and gup.)
Just downloaded the portable version of Zeroinstall (2.9.7), and copied the gup command to it:

    0install add gup http://gfxmonk.net/dist/0install/gup.xml

only to get: 

    Try 0install --help
    Too many arguments or unknown options.
            http://gfxmonk.net/dist/0install/gup.xml

Would there be something to change in the README regarding this problem?

(HINT: '--help' does not mention "add", but there's an "alias" command.
ALSO: the portable ZeroInstall here says it cannot do aliasing at all without being installed. :-/ 
You might wish to mention these pitfalls in the README. Cheers!)

**Comment by timbertson** [comment]
Hmm, as far as I know `0install add` is present in all versions of the `0install` command. So I suspect it's either a difference in the portable or windows version.

The docs for the windows version[0] definitely show `0install add`, so I don't know why `--help` wouldn't. It is listed on linux, perhaps the windows version only shows a subset of commands?

I suspect the windows version may only take the feed URL - i.e. try running:

    0install add http://gfxmonk.net/dist/0install/gup.xml

I'm afraid I don't know how it then integrates with the desktop environment (and $PATH) - perhaps you could give it a try and let me know whether it makes a `gup` executable available?

I know that `0install run http://gfxmonk.net/dist/0install/gup.xml` should definitely work cross platform, but that's obviously inconvenient.

[0]: https://0install.de/docs/commands/

**Comment by lunakid** [comment]
Strange indeed. Thanks anyway, perhaps I'll just bite the bullet and install it normally. (That was my wife's machine, so I naturally opted for the portable version.)

**Comment by lunakid** [comment]
OK, installed ZeroInstall, and gup now "exists" in my toolset.
